"""
This project uses random module in Python to randomly generate an integer between 1 and 1000. Note that
the number is unknown to the user, and he/she should guess what that number is in a maximum of 5 guesses.
If the users guess is wrong, the program should provide some sort of indication as to how wrong (e.g., The
number is too high or too low). After each wrong guess, the program should also print how many attempts are
left for the user to guess the number again. If the user cannot guess the correct number in five attempts, the
program should print the message “Sorry!! You did not manage to guess the number. You have reached
the guessing limit” and prints the number itself. If the user guesses correctly (in maximum five attempts),
the program should print the message “Congratulation! You guessed the number in ** attempt(s)” (the
number of attempts used to guess the number should be printed instead of **). The program should also print
the number itself in the end. Finally, the program should ask the user if he/she wants to play the game again.
If the answer is “YES”, the user must be able to play the game (a new game) again and has 5 attempts to guess
a new number randomly generated by the program. The program should be repeated as long as the user wants
to play the game again and again.

"""

from random import randint


def menu():
     print("\n Welcome to the game!")
     game()

def game():
    randomNumber = randint(1,1000)
    attempts = 0
    maxAttempts = 5

    while attempts < maxAttempts:
        userInput = int(input("Guess what the number is from 1 - 1000: "))

        if userInput < 1 or userInput > 1000:
            print("Enter valid number!")
        elif userInput == randomNumber:
            attempts += 1
            print(f"Congratulation! You guessed the random number {randomNumber}, in {attempts} attempt(s)")
        elif attempts == maxAttempts - 1:
            attempts += 1
            print(f"Sorry!! You did not manage to guess the number {randomNumber}. You have reached the guessing limit {attempts} attempts \n")
        elif userInput > randomNumber:
             attempts += 1
             print(f"The number is too high. You have {maxAttempts - attempts} attempts left.")
        elif userInput < randomNumber:
            attempts += 1
            print(f"the number is too low. You have {maxAttempts - attempts} attempts left")
    else:
        playAgain = int(input("Do you want to play again? \n 1= yes 2= exit: "))
        if playAgain == 1:
            menu()
        else:
            print("Good bye!")
                                     
menu()


